'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const source=fs.readFileSync(path.join(__dirname,'../src/trainer.js'),'utf8');
const start=source.indexOf('function renderQuestionFeedback(');
const end=source.indexOf('\nfunction questionFeedback(',start);
const skills=['BN01_TREBLE_PITCH','BN06_STEM_DIRECTION','RH01_DURATION_VALUE','GR02_PRIMARY_BEAM','MS03_SCALE_ACCIDENTAL'];
const context=vm.createContext({QUESTION_ERROR_PRIORITY:skills,state:{sessionResults:[],questionIndex:0},feedbackSkillName:x=>x,feedbackEscapeHtml:x=>String(x).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')});
vm.runInContext(source.slice(start,end),context);
const errors=skills.flatMap(skillCode=>Array.from({length:15},(_,i)=>({skillCode,message:`${skillCode}: โน้ตตำแหน่ง ${i+1}: ควรเป็น A♯; พบ ไม่มีเครื่องหมายแปลงเสียง`})));
context.result={skills:[],errors};
const html=vm.runInContext('renderQuestionFeedback(result)',context);
assert.equal((html.match(/<li>/g)||[]).length,75);
assert.equal((html.match(/class="df-diagnostic-item"/g)||[]).length,5);
errors.forEach(error=>assert(html.includes(error.message)));
assert(!html.includes('และอีก'));
context.result={skills:[],errors:[{skillCode:skills[0],message:'<img src=x onerror=alert(1)>'}]};
assert(vm.runInContext('renderQuestionFeedback(result)',context).includes('&lt;img'));
context.result={skills:[],errors:[]};
assert(vm.runInContext('renderQuestionFeedback(result)',context).includes('ไม่พบข้อผิดพลาด'));
console.log('PASS all 75 details across 5 skills, final position, escaped messages, and correct-answer feedback');
