'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(__dirname,'..'),read=rel=>fs.readFileSync(path.join(root,rel),'utf8');
const source=read('src/domain/notation/notation-renderer.js');
assert(!/supabase|fetch\s*\(|XMLHttpRequest|WebSocket|\beval\s*\(|new Function|import\s*\(|MAJOR_SCALE_NOTATION|LEVEL_KEYS|STAGE_[1-4]/i.test(source),'renderer must stay presentation-only');
const document={createElementNS(ns,name){return{ns,name,attrs:{},textContent:'',setAttribute(k,v){this.attrs[k]=v;}};}};
const ctx={window:{},document};vm.createContext(ctx);vm.runInContext(source,ctx,{filename:'notation-renderer.js'});
const api=ctx.window.MajorScaleApp.notationRenderer;assert(api&&Object.isFrozen(api));
const mkSvg=()=>({children:[],appendChild(n){this.children.push(n);}});
let svg=mkSvg();api.drawStaffLines(svg,{x1:10,x2:110,top:20,spacing:8},{strokeWidth:2});
assert.equal(svg.children.length,5);assert.deepStrictEqual(svg.children.map(n=>[n.attrs.x1,n.attrs.x2,n.attrs.y1,n.attrs.y2,n.attrs['stroke-width']]),[[10,110,20,20,2],[10,110,28,28,2],[10,110,36,36,2],[10,110,44,44,2],[10,110,52,52,2]]);
svg=mkSvg();api.drawBarline(svg,80,{top:20,spacing:8},{strokeWidth:1.5});assert.deepStrictEqual([svg.children[0].attrs.x1,svg.children[0].attrs.y1,svg.children[0].attrs.y2,svg.children[0].attrs['stroke-width']],[80,20,52,1.5]);
svg=mkSvg();api.drawDoubleBarline(svg,90,96,{top:20,spacing:8});assert.equal(svg.children.length,2);assert.deepStrictEqual(svg.children.map(n=>[n.attrs.x1,n.attrs['stroke-width']]),[[90,1.4],[96,3.2]]);
let positions=[0,0,0];api.layoutMeasureWithinBounds([0,1,2],100,300,{leadingPad:10,trailingPad:10,preferredGap:20,minimumGap:5,edgeShareMax:10,leftExtents:[10,10,10],rightExtents:[10,10,10],basePositions:[120,180,260],positions});
assert(positions[0]-10>=110-1e-9);assert(positions[2]+10<=290+1e-9);assert(positions[0]<positions[1]&&positions[1]<positions[2]);
positions=[0];api.layoutMeasureWithinBounds([0],100,160,{leadingPad:10,trailingPad:10,preferredGap:20,minimumGap:5,edgeShareMax:10,leftExtents:[12],rightExtents:[12],basePositions:[500],positions});assert.equal(positions[0],138);
const trainer=read('src/trainer.js');
for(const expected of ['notationRenderer.drawStaffLines(svg,staff','notationRenderer.drawBarline(svg,x,staff','notationRenderer.drawDoubleBarline(svg,1350,1358,staff)','notationRenderer.layoutMeasureWithinBounds(indices,leftBoundary,rightBoundary'])assert(trainer.includes(expected),'missing score-layout delegation: '+expected);
for(const protectedMarker of ['function drawBeams(){','scoreSvg.addEventListener("pointerdown"','function render(){'])assert(trainer.includes(protectedMarker),'critical interaction/beaming runtime must remain: '+protectedMarker);
console.log('PASS notation renderer score layout: staff frame, barlines, bounded horizontal slots, trainer delegation and protected interaction/beaming boundaries');
