'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(__dirname,'..'),read=rel=>fs.readFileSync(path.join(root,rel),'utf8');
const source=read('src/domain/notation/notation-renderer.js');
assert(!/supabase|fetch\s*\(|XMLHttpRequest|WebSocket|\beval\s*\(|new Function|import\s*\(|MAJOR_SCALE_NOTATION|LEVEL_KEYS|STAGE_[1-4]/i.test(source),'renderer must stay presentation-only');
const document={createElementNS(ns,name){return{ns,name,attrs:{},textContent:'',setAttribute(k,v){this.attrs[k]=v;},remove(){if(this.parent&&this.parent.children){const i=this.parent.children.indexOf(this);if(i>=0)this.parent.children.splice(i,1);}},getBBox(){return this.box||{x:0,y:-60,width:40,height:80};}};}};
const ctx={window:{},document,console};vm.createContext(ctx);vm.runInContext(source,ctx,{filename:'notation-renderer.js'});
const api=ctx.window.MajorScaleApp.notationRenderer;assert(api&&Object.isFrozen(api));
const smufl={noteheadWhole:'W',noteheadHalf:'H',noteheadBlack:'B',flag8thUp:'8U',flag8thDown:'8D',flag16thUp:'16U',flag16thDown:'16D',accidentalFlat:'FL',accidentalNatural:'N',accidentalSharp:'SH',accidentalDoubleSharp:'DS',accidentalDoubleFlat:'DF'};
function mkSvg(box={x:-2,y:-20,width:20,height:40}){return{children:[],appendChild(n){n.parent=this;n.box=box;this.children.push(n);return n;}};}
function group(){return{children:[],appendChild(n){this.children.push(n);return n;}};}
let svg=mkSvg({x:-3,y:-25,width:18,height:45});
assert.deepStrictEqual(JSON.parse(JSON.stringify(api.measureSvgTextGlyph(svg,'X',72,'TrainerBravura'))),{x:-3,y:-25,width:18,height:45});
assert.equal(svg.children.length,0,'measurement probe removed');
svg=mkSvg({x:-2,y:-20,width:24,height:40});
assert.equal(api.noteheadHalfWidthForRhythm(svg,'whole',{smufl,fontSize:72,fontFamily:'TrainerBravura'}),12);
assert.equal(api.noteheadHalfWidthForRhythm(svg,'quarter',{smufl,fontSize:72,fontFamily:'TrainerBravura'}),10.8);
let g=group();svg=mkSvg({x:-2,y:-20,width:24,height:40});
api.drawNotehead(g,svg,100,120,'whole','#111',{smufl,fontSize:72,fontFamily:'TrainerBravura'});
assert.equal(g.children.length,1);assert.equal(g.children[0].name,'text');assert.equal(g.children[0].textContent,'W');assert.equal(g.children[0].attrs.x,90);assert.equal(g.children[0].attrs.y,120);
g=group();api.drawNotehead(g,svg,100,120,'quarter','#111',{smufl,fontSize:72,fontFamily:'TrainerBravura'});
assert.equal(g.children[0].name,'ellipse');assert.deepStrictEqual(g.children[0].attrs,{cx:100,cy:120,rx:10.8,ry:7.2,fill:'#111',stroke:'#111','stroke-width':2,transform:'rotate(-18 100 120)'});
g=group();svg=mkSvg({x:-2,y:-20,width:20,height:40});
api.drawAccidentalForNote(g,svg,'#',100,120,'#111','quarter',{smufl,fontSize:72,fontFamily:'TrainerBravura',accidentalToNoteGap:5});
assert.equal(g.children.length,1);assert.equal(g.children[0].textContent,'SH');assert.equal(g.children[0].attrs.x,66.2);assert.equal(g.children[0].attrs.y,120);
g=group();api.drawStemAndFlag(g,100,120,'quarter','#111','up',null,{smufl,fontSize:72,fontFamily:'TrainerBravura'});
assert.equal(g.children.length,1);assert.deepStrictEqual(g.children[0].attrs,{x1:110,y1:120,x2:110,y2:65,stroke:'#111','stroke-width':2.3});
g=group();api.drawStemAndFlag(g,100,120,'eighth','#111','down',null,{smufl,fontSize:72,fontFamily:'TrainerBravura'});
assert.equal(g.children.length,2);assert.equal(g.children[1].textContent,'8D');assert.equal(g.children[1].attrs.x,90);assert.equal(g.children[1].attrs.y,175);
g=group();api.drawStemAndFlag(g,100,120,'sixteenth','#111','up','beam-1',{smufl,fontSize:72,fontFamily:'TrainerBravura'});assert.equal(g.children.length,0,'beamed short note leaves stem/beam rendering to beam engine');
const trainer=read('src/trainer.js');
assert(trainer.includes('return notationRenderer.measureSvgTextGlyph'));
assert(trainer.includes('return notationRenderer.noteheadHalfWidthForRhythm'));
assert(trainer.includes('return notationRenderer.drawAccidentalForNote'));
assert(trainer.includes('notationRenderer.drawNotehead(g,svg,x,y,n.rhythm,fill'));
assert(trainer.includes('const dir=groupItems.length>1 ? getBeamDirection(groupItems)'));
assert(trainer.includes('notationRenderer.drawStemAndFlag(g,x,y,n.rhythm,fill,dir,n.beamGroup'));
for(const forbidden of ['function drawBeams(){','scoreSvg.addEventListener("pointerdown"','function check(){'])assert(trainer.includes(forbidden),'critical legacy runtime must remain: '+forbidden);
console.log('PASS notation renderer note primitives: glyph measurement, noteheads, accidentals, stems/flags, wrappers and beam/interaction boundaries');
