'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(__dirname,'..'),read=rel=>fs.readFileSync(path.join(root,rel),'utf8');
const source=read('src/domain/notation/notation-renderer.js');
assert(!/supabase|fetch\s*\(|XMLHttpRequest|WebSocket|\beval\s*\(|new Function|import\s*\(|MAJOR_SCALE_NOTATION|LEVEL_KEYS|STAGE_[1-4]/i.test(source),'renderer must stay presentation-only');
const document={createElementNS(ns,name){return{ns,name,attrs:{},textContent:'',setAttribute(k,v){this.attrs[k]=v;}};}};
const ctx={window:{},document};vm.createContext(ctx);vm.runInContext(source,ctx,{filename:'notation-renderer.js'});
const api=ctx.window.MajorScaleApp.notationRenderer;assert(api&&Object.isFrozen(api));
const mkSvg=()=>({children:[],appendChild(n){this.children.push(n);}});
let svg=mkSvg();
api.drawKeySignature(svg,{type:'sharp',acc:2},'shown',{top:100,spacing:20,sigX:130},{sharpOrder:['F','C','G','D','A','E','B'],flatOrder:['B','E','A','D','G','C','F'],sharpGlyph:'S',flatGlyph:'F',fontSize:80,fontFamily:'TrainerBravura',advance:21});
assert.equal(svg.children.length,2);assert.deepStrictEqual(svg.children.map(n=>n.textContent),['S','S']);
assert.deepStrictEqual(svg.children.map(n=>[n.attrs.x,n.attrs.y]),[[130,100],[151,130]]);
svg=mkSvg();api.drawKeySignature(svg,{type:'flat',acc:2},'hidden',{top:100,spacing:20,sigX:130},{sharpOrder:['F'],flatOrder:['B','E'],sharpGlyph:'S',flatGlyph:'F',fontSize:80,fontFamily:'TrainerBravura',advance:21});assert.equal(svg.children.length,0);
svg=mkSvg();api.drawKeySignature(svg,{type:'flat',acc:2},'shown',{top:100,spacing:20,sigX:130},{sharpOrder:['F'],flatOrder:['B','E'],sharpGlyph:'S',flatGlyph:'F',fontSize:80,fontFamily:'TrainerBravura',advance:21});assert.deepStrictEqual(svg.children.map(n=>[n.textContent,n.attrs.x,n.attrs.y]),[['F',130,140],['F',151,110]]);
const nodes=[{getBBox:()=>({x:10,width:20})},{getBBox:()=>({x:35,width:12})},{getBBox(){throw new Error('hidden')}}];
assert.equal(api.rightEdgeOfSvgClass({querySelectorAll(sel){assert.equal(sel,'.time-signature-glyph');return nodes;}},'time-signature-glyph'),47);
assert.equal(api.rightEdgeOfSvgClass({querySelectorAll(){return[];}},'x'),null);
svg=mkSvg();api.drawTimeSignature(svg,{top:100,spacing:20},150,{glyph:'4',fontSize:80,fontFamily:'TrainerBravura',measureText(){return{x:-3,y:-20,width:15,height:40};}});
assert.equal(svg.children.length,2);assert.deepStrictEqual(svg.children.map(n=>[n.textContent,n.attrs.x,n.attrs.y]),[['4',153,120],['4',153,160]]);
const trainer=read('src/trainer.js');
assert(trainer.includes('return notationRenderer.drawKeySignature'));assert(trainer.includes('return notationRenderer.rightEdgeOfSvgClass'));assert(trainer.includes('return notationRenderer.drawTimeSignature'));
for(const forbidden of ['function drawBeams(){','function render(){','scoreSvg.addEventListener("pointerdown"'])assert(trainer.includes(forbidden),'critical legacy runtime must remain: '+forbidden);
console.log('PASS notation renderer static signatures: key signature, time signature, measured right edge, wrappers and critical legacy boundaries');
