'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..'),read=file=>fs.readFileSync(path.join(root,file),'utf8');
const repo=read('src/data/dashboard.repository.js');
const student=read('src/dashboard/student-dashboard-v2.js');
const teacher=read('src/dashboard/teacher-dashboard.js');
const migration=read('supabase/migrations/20260913110000_profile_system.sql');
for(const field of ['display_name','student_id','program','year_level','section','avatar_url']) assert(migration.includes(field),`migration must add ${field}`);
assert(migration.includes('revoke update on public.profiles from anon, authenticated'));
assert(migration.includes('grant update (full_name, display_name, student_id, program, year_level, section, avatar_url)'));
assert(migration.includes("teacher.membership_role = 'teacher'"));
assert(migration.includes('target.user_id = profiles.id'));
assert(repo.includes('updateStudentProfile'));
assert(repo.includes('getTeacherStudentProfile'));
assert(student.includes('id="sd2ProfileForm"'));
assert(student.includes('name="full_name"'));
assert(student.includes('name="display_name"'));
assert(student.includes('name="avatar_url"'));
assert(student.includes('repo.updateStudentProfile'));
assert(!student.match(/updateStudentProfile[\s\S]{0,1500}role/), 'student update payload must not include role');
assert(teacher.includes('getTeacherStudentProfile'));
assert(teacher.includes('teacher-profile-summary'));
assert(teacher.includes('Learning Progress'));
console.log('PASS profile system contract: editable own fields, Auth email separation, teacher detail profile and relationship-boundary hooks');
